[package]
name = "sifive"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
edition = "2018"

[dependencies]
riscv = { path = "../../arch/riscv" }
kernel = { path = "../../kernel" }

